//api url
export const API_URL = 'http://localhost:3012';
export const TEST_TOKEN = 'Bearer $2b$10$B5i14s7I4YGlbIhZ6B5Byer5qdFgpAyOylxnyxdXBedZmP0oe0kce';

export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_RESPONSE = 'FETCH_PROJECTS_RESPONSE';
export const FETCH_PROJECTS_DEV_REQUEST = 'FETCH_PROJECTS_DEV_REQUEST';
export const FETCH_PROJECTS_DEV_RESPONSE = 'FETCH_PROJECTS_DEV_RESPONSE';
export const ADD_PROJECT_REQUEST = 'ADD_PROJECT_REQUEST';
export const ADD_PROJECT_RESPONSE = 'ADD_PROJECT_RESPONSE';
export const ADD_DEV_TO_PROJECT_REQUEST = 'ADD_DEV_TO_PROJECT_REQUEST';
export const ADD_DEV_TO_PROJECT_RESPONSE = 'ADD_DEV_TO_PROJECT_RESPONSE';
export const SEARCH_DEVELOPER_REQUEST = 'SEARCH_DEVELOPER_REQUEST';
export const SEARCH_DEVELOPER_RESPONSE = 'SEARCH_DEVELOPER_RESPONSE';
export const SET_CUR_PROJECT_ID = 'SET_CUR_PROJECT_ID';

export const FETCH_TASKS_REQUEST = 'FETCH_TASKS_REQUEST';
export const FETCH_TASKS_RESPONSE = 'FETCH_TASKS_RESPONSE';
export const ADD_TASK_REQUEST = 'ADD_TASK_REQUEST';
export const ADD_TASK_RESPONSE = 'ADD_TASK_RESPONSE';
export const CHANGE_STATUS_TASK_REQUEST = 'CHANGE_STATUS_TASK_REQUEST';
export const CHANGE_STATUS_TASK_RESPONSE = 'CHANGE_STATUS_TASK_RESPONSE';
export const SET_DEVELOPER_TASK_REQUEST = 'SET_DEVELOPER_TASK_REQUEST';
export const SET_DEVELOPER_TASK_RESPONSE = 'SET_DEVELOPER_TASK_RESPONSE';

export const FETCH_USER_REQUEST = 'FETCH_USER_REQUEST';
export const FETCH_USER_RESPONSE = 'FETCH_USER_RESPONSE';
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST';
export const REGISTER_USER_RESPONSE = 'REGISTER_USER_RESPONSE';
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_RESPONSE = 'LOGIN_USER_RESPONSE';
export const LOGOUT_USER = 'LOGOUT_USER';


export const FETCH_COMMENTS_REQUEST = 'FETCH_COMMENTS_REQUEST';
export const FETCH_COMMENTS_RESPONSE = 'FETCH_COMMENTS_RESPONSE';
export const ADD_COMMENT_REQUEST = 'ADD_COMMENT_REQUEST';
export const ADD_COMMENT_RESPONSE = 'ADD_COMMENT_RESPONSE';
export const DELETE_COMMENT_REQUEST = 'DELETE_COMMENT_REQUEST';
export const DELETE_COMMENT_RESPONSE = 'DELETE_COMMENT_RESPONSE';
export const UPDATE_COMMENT_REQUEST = 'UPDATE_COMMENT_REQUEST';
export const UPDATE_COMMENT_RESPONSE = 'UPDATE_COMMENT_RESPONSE';